"""new fields in project model

Revision ID: 5b6f5a65f433
Revises: 758edb381ded
Create Date: 2018-08-08 14:28:12.240356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6f5a65f433'
down_revision = '758edb381ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_name', table_name='project')
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.create_index('ix_project_name', 'project', ['name'], unique=1)
    # ### end Alembic commands ###
