"""new fields in device model

Revision ID: 758edb381ded
Revises: 265ed985de18
Create Date: 2018-08-08 09:17:37.984142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758edb381ded'
down_revision = '265ed985de18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('status', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'status')
    # ### end Alembic commands ###
