"""new name for device model

Revision ID: ca0a780a134c
Revises: 788ff3bb1518
Create Date: 2018-09-13 15:12:26.100762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0a780a134c'
down_revision = '788ff3bb1518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adb_sn', sa.String(length=128), nullable=True),
    sa.Column('constructor', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('imei', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_model_adb_sn'), 'device_model', ['adb_sn'], unique=True)
    op.create_index(op.f('ix_device_model_imei'), 'device_model', ['imei'], unique=True)
    op.create_index(op.f('ix_device_model_timestamp'), 'device_model', ['timestamp'], unique=False)
    op.drop_index('ix_device_adb_sn', table_name='device')
    op.drop_index('ix_device_imei', table_name='device')
    op.drop_index('ix_device_timestamp', table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('adb_sn', sa.VARCHAR(length=128), nullable=True),
    sa.Column('constructor', sa.VARCHAR(length=64), nullable=True),
    sa.Column('model', sa.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('imei', sa.VARCHAR(length=128), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], [u'project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_timestamp', 'device', ['timestamp'], unique=False)
    op.create_index('ix_device_imei', 'device', ['imei'], unique=1)
    op.create_index('ix_device_adb_sn', 'device', ['adb_sn'], unique=1)
    op.drop_index(op.f('ix_device_model_timestamp'), table_name='device_model')
    op.drop_index(op.f('ix_device_model_imei'), table_name='device_model')
    op.drop_index(op.f('ix_device_model_adb_sn'), table_name='device_model')
    op.drop_table('device_model')
    # ### end Alembic commands ###
