"""new fields p in project model

Revision ID: dd4e694b3acf
Revises: 966b658403b2
Create Date: 2018-08-09 13:10:41.624416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4e694b3acf'
down_revision = '966b658403b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'path')
    # ### end Alembic commands ###
